/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * QubitLearn AI — Multi-Framework Transpiler
 * Aligned strictly with 10 Quantum SDKs and export formats:
 * 1. Qiskit 1.x (IBM)
 * 2. Cirq (Google Quantum AI)
 * 3. PennyLane (Xanadu)
 * 4. Amazon Braket (AWS)
 * 5. NVIDIA CUDA-Q (CUDA Quantum)
 * 6. Microsoft Q# (Azure Quantum)
 * 7. pyQuil (Rigetti Forest)
 * 8. QuTiP (Quantum Toolbox in Python)
 * 9. OpenQASM 3.0 / 2.0
 * 10. Publication LaTeX quantikz
 */

import { CircuitState, GatePlacement } from '../types';

export class CircuitTranspiler {
  /**
   * 1. Transpile to Qiskit (Python)
   */
  static toQiskit(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — Qiskit SDK',
      'from qiskit import QuantumCircuit, transpile',
      'from qiskit_aer import AerSimulator',
      '',
      `# Initialize quantum circuit with ${numQubits} qubits and classical registers`,
      `qc = QuantumCircuit(${numQubits}, ${numQubits})`,
      '',
    ];

    for (const g of sorted) {
      lines.push(this.gateToQiskit(g));
    }

    lines.push('');
    lines.push('# Simulate on Qiskit Aer Statevector Simulator');
    lines.push('simulator = AerSimulator()');
    lines.push('qc.save_statevector()');
    lines.push('compiled_circuit = transpile(qc, simulator)');
    lines.push('job = simulator.run(compiled_circuit)');
    lines.push('result = job.result()');
    lines.push('statevector = result.get_statevector(qc)');
    lines.push('print("Final Statevector:\\n", statevector)');
    lines.push('print("Measurement Counts:\\n", result.get_counts())');

    return lines.join('\n');
  }

  private static gateToQiskit(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    const cQ = controlQubit !== undefined ? controlQubit : (qubit === 0 ? 1 : 0);
    const tQ = targetQubit !== undefined ? targetQubit : (qubit === 0 ? 1 : 0);
    const c2Q = controlQubit2 !== undefined ? controlQubit2 : (qubit <= 1 ? 2 : 0);
    const safeParam = isNaN(param) ? 0 : param;

    switch (type) {
      case 'H':
        return `qc.h(${qubit})`;
      case 'X':
        return `qc.x(${qubit})`;
      case 'Y':
        return `qc.y(${qubit})`;
      case 'Z':
        return `qc.z(${qubit})`;
      case 'S':
        return `qc.s(${qubit})`;
      case 'T':
        return `qc.t(${qubit})`;
      case 'Sdg':
        return `qc.sdg(${qubit})`;
      case 'Tdg':
        return `qc.tdg(${qubit})`;
      case 'Rx':
        return `qc.rx(${safeParam.toFixed(4)}, ${qubit})`;
      case 'Ry':
        return `qc.ry(${safeParam.toFixed(4)}, ${qubit})`;
      case 'Rz':
        return `qc.rz(${safeParam.toFixed(4)}, ${qubit})`;
      case 'CX':
        return `qc.cx(${cQ}, ${qubit})`;
      case 'CZ':
        return `qc.cz(${cQ}, ${qubit})`;
      case 'SWAP':
        return `qc.swap(${qubit}, ${tQ})`;
      case 'CCX':
        return `qc.ccx(${cQ}, ${c2Q}, ${qubit})`;
      case 'M':
        return `qc.measure(${qubit}, ${qubit})`;
      default:
        return `# Unsupported gate: ${type}`;
    }
  }

  /**
   * 2. Transpile to Cirq (Google Quantum AI)
   */
  static toCirq(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — Cirq SDK',
      'import cirq',
      '',
      `# Define ${numQubits} line qubits`,
      `qubits = [cirq.LineQubit(i) for i in range(${numQubits})]`,
      'circuit = cirq.Circuit()',
      '',
    ];

    for (const g of sorted) {
      lines.push(this.gateToCirq(g));
    }

    lines.push('');
    lines.push('# Run simulation');
    lines.push('sim = cirq.Simulator()');
    lines.push('result = sim.simulate(circuit)');
    lines.push('print("Cirq Final State:\\n", result.state_vector())');

    return lines.join('\n');
  }

  private static gateToCirq(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    const cQ = controlQubit !== undefined ? controlQubit : (qubit === 0 ? 1 : 0);
    const tQ = targetQubit !== undefined ? targetQubit : (qubit === 0 ? 1 : 0);
    const c2Q = controlQubit2 !== undefined ? controlQubit2 : (qubit <= 1 ? 2 : 0);
    const safeParam = isNaN(param) ? 0 : param;

    switch (type) {
      case 'H':
        return `circuit.append(cirq.H(qubits[${qubit}]))`;
      case 'X':
        return `circuit.append(cirq.X(qubits[${qubit}]))`;
      case 'Y':
        return `circuit.append(cirq.Y(qubits[${qubit}]))`;
      case 'Z':
        return `circuit.append(cirq.Z(qubits[${qubit}]))`;
      case 'S':
        return `circuit.append(cirq.S(qubits[${qubit}]))`;
      case 'T':
        return `circuit.append(cirq.T(qubits[${qubit}]))`;
      case 'Rx':
        return `circuit.append(cirq.rx(${safeParam.toFixed(4)})(qubits[${qubit}]))`;
      case 'Ry':
        return `circuit.append(cirq.ry(${safeParam.toFixed(4)})(qubits[${qubit}]))`;
      case 'Rz':
        return `circuit.append(cirq.rz(${safeParam.toFixed(4)})(qubits[${qubit}]))`;
      case 'CX':
        return `circuit.append(cirq.CNOT(qubits[${cQ}], qubits[${qubit}]))`;
      case 'CZ':
        return `circuit.append(cirq.CZ(qubits[${cQ}], qubits[${qubit}]))`;
      case 'SWAP':
        return `circuit.append(cirq.SWAP(qubits[${qubit}], qubits[${tQ}]))`;
      case 'CCX':
        return `circuit.append(cirq.TOFFOLI(qubits[${cQ}], qubits[${c2Q}], qubits[${qubit}]))`;
      case 'M':
        return `circuit.append(cirq.measure(qubits[${qubit}], key='m_${qubit}'))`;
      default:
        return `# Unsupported gate: ${type}`;
    }
  }

  /**
   * 3. Transpile to PennyLane (Python)
   */
  static toPennyLane(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — PennyLane Quantum SDK',
      'import pennylane as qml',
      'import numpy as np',
      '',
      `dev = qml.device("default.qubit", wires=${numQubits})`,
      '',
      '@qml.qnode(dev)',
      'def quantum_circuit():',
    ];

    if (sorted.length === 0) {
      lines.push('    return qml.state()');
    } else {
      for (const g of sorted) {
        lines.push(`    ${this.gateToPennyLane(g)}`);
      }
      lines.push('    return qml.state()');
    }

    lines.push('');
    lines.push('state = quantum_circuit()');
    lines.push('print("PennyLane Computed State:\\n", state)');
    lines.push('print("Probabilities:\\n", np.abs(state)**2)');

    return lines.join('\n');
  }

  private static gateToPennyLane(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    const cQ = controlQubit !== undefined ? controlQubit : (qubit === 0 ? 1 : 0);
    const tQ = targetQubit !== undefined ? targetQubit : (qubit === 0 ? 1 : 0);
    const c2Q = controlQubit2 !== undefined ? controlQubit2 : (qubit <= 1 ? 2 : 0);
    const safeParam = isNaN(param) ? 0 : param;

    switch (type) {
      case 'H':
        return `qml.Hadamard(wires=${qubit})`;
      case 'X':
        return `qml.PauliX(wires=${qubit})`;
      case 'Y':
        return `qml.PauliY(wires=${qubit})`;
      case 'Z':
        return `qml.PauliZ(wires=${qubit})`;
      case 'S':
        return `qml.S(wires=${qubit})`;
      case 'T':
        return `qml.T(wires=${qubit})`;
      case 'Sdg':
        return `qml.adjoint(qml.S(wires=${qubit}))`;
      case 'Tdg':
        return `qml.adjoint(qml.T(wires=${qubit}))`;
      case 'Rx':
        return `qml.RX(${safeParam.toFixed(4)}, wires=${qubit})`;
      case 'Ry':
        return `qml.RY(${safeParam.toFixed(4)}, wires=${qubit})`;
      case 'Rz':
        return `qml.RZ(${safeParam.toFixed(4)}, wires=${qubit})`;
      case 'CX':
        return `qml.CNOT(wires=[${cQ}, ${qubit}])`;
      case 'CZ':
        return `qml.CZ(wires=[${cQ}, ${qubit}])`;
      case 'SWAP':
        return `qml.SWAP(wires=[${qubit}, ${tQ}])`;
      case 'CCX':
        return `qml.Toffoli(wires=[${cQ}, ${c2Q}, ${qubit}])`;
      case 'M':
        return `# Measurement on wire ${qubit}`;
      default:
        return `# Unsupported gate: ${type}`;
    }
  }

  /**
   * 4. Transpile to Amazon Braket (AWS Python SDK)
   */
  static toBraket(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — Amazon Braket Quantum SDK',
      'from braket.circuits import Circuit',
      'from braket.devices import LocalSimulator',
      'import numpy as np',
      '',
      `# Initialize Braket quantum circuit for ${numQubits} qubits`,
      'circuit = Circuit()',
      '',
    ];

    for (const g of sorted) {
      lines.push(this.gateToBraket(g));
    }

    lines.push('');
    lines.push('# Run statevector simulation on AWS Braket Local Simulator');
    lines.push('device = LocalSimulator()');
    lines.push('circuit.state_vector()  # Request exact statevector observable');
    lines.push('task = device.run(circuit, shots=0)');
    lines.push('result = task.result()');
    lines.push('print("Amazon Braket Statevector:\\n", result.values[0])');
    lines.push('print("\\nCircuit Diagram:\\n", circuit)');

    return lines.join('\n');
  }

  private static gateToBraket(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    switch (type) {
      case 'H':
        return `circuit.h(${qubit})`;
      case 'X':
        return `circuit.x(${qubit})`;
      case 'Y':
        return `circuit.y(${qubit})`;
      case 'Z':
        return `circuit.z(${qubit})`;
      case 'S':
        return `circuit.s(${qubit})`;
      case 'T':
        return `circuit.t(${qubit})`;
      case 'Sdg':
        return `circuit.si(${qubit})`;
      case 'Tdg':
        return `circuit.ti(${qubit})`;
      case 'Rx':
        return `circuit.rx(${qubit}, ${param.toFixed(4)})`;
      case 'Ry':
        return `circuit.ry(${qubit}, ${param.toFixed(4)})`;
      case 'Rz':
        return `circuit.rz(${qubit}, ${param.toFixed(4)})`;
      case 'CX':
        return `circuit.cnot(${controlQubit}, ${qubit})`;
      case 'CZ':
        return `circuit.cz(${controlQubit}, ${qubit})`;
      case 'SWAP':
        return `circuit.swap(${qubit}, ${targetQubit})`;
      case 'CCX':
        return `circuit.ccnot(${controlQubit}, ${controlQubit2}, ${qubit})`;
      case 'M':
        return `# Measurement on qubit ${qubit} handled by shots`;
      default:
        return `# Unsupported gate: ${type}`;
    }
  }

  /**
   * 5. Transpile to NVIDIA CUDA-Q (CUDA Quantum)
   */
  static toCudaQ(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — NVIDIA CUDA-Q SDK',
      'import cudaq',
      '',
      `# Define quantum kernel with ${numQubits} qubits`,
      '@cudaq.kernel',
      'def quantum_kernel():',
      `    q = cudaq.qvector(${numQubits})`,
    ];

    if (sorted.length === 0) {
      lines.push('    pass');
    } else {
      for (const g of sorted) {
        lines.push(`    ${this.gateToCudaQ(g)}`);
      }
    }

    lines.push('');
    lines.push('# Run simulation with NVIDIA cuStateVec / QPP backend');
    lines.push('state = cudaq.get_state(quantum_kernel)');
    lines.push('print("CUDA-Q Statevector:\\n", state)');
    lines.push('counts = cudaq.sample(quantum_kernel, shots_count=1024)');
    lines.push('print("Measurement Counts:\\n", counts)');

    return lines.join('\n');
  }

  private static gateToCudaQ(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    switch (type) {
      case 'H':
        return `cudaq.h(q[${qubit}])`;
      case 'X':
        return `cudaq.x(q[${qubit}])`;
      case 'Y':
        return `cudaq.y(q[${qubit}])`;
      case 'Z':
        return `cudaq.z(q[${qubit}])`;
      case 'S':
        return `cudaq.s(q[${qubit}])`;
      case 'T':
        return `cudaq.t(q[${qubit}])`;
      case 'Sdg':
        return `cudaq.sdg(q[${qubit}])`;
      case 'Tdg':
        return `cudaq.tdg(q[${qubit}])`;
      case 'Rx':
        return `cudaq.rx(${param.toFixed(4)}, q[${qubit}])`;
      case 'Ry':
        return `cudaq.ry(${param.toFixed(4)}, q[${qubit}])`;
      case 'Rz':
        return `cudaq.rz(${param.toFixed(4)}, q[${qubit}])`;
      case 'CX':
        return `cudaq.cx(q[${controlQubit}], q[${qubit}])`;
      case 'CZ':
        return `cudaq.cz(q[${controlQubit}], q[${qubit}])`;
      case 'SWAP':
        return `cudaq.swap(q[${qubit}], q[${targetQubit}])`;
      case 'CCX':
        return `cudaq.ccx(q[${controlQubit}], q[${controlQubit2}], q[${qubit}])`;
      case 'M':
        return `cudaq.mz(q[${qubit}])`;
      default:
        return `# Unsupported gate: ${type}`;
    }
  }

  /**
   * 6. Transpile to Microsoft Q# (Azure Quantum)
   */
  static toQSharp(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '// Generated by QubitLearn AI — Microsoft Q# / Azure Quantum SDK',
      'namespace QubitLearn.QuantumCircuit {',
      '    open Microsoft.Quantum.Intrinsic;',
      '    open Microsoft.Quantum.Canon;',
      '    open Microsoft.Quantum.Measurement;',
      '    open Microsoft.Quantum.Diagnostics;',
      '',
      '    @EntryPoint()',
      '    operation RunCircuit() : Result[] {',
      `        use qs = Qubit[${numQubits}];`,
      '',
    ];

    for (const g of sorted) {
      lines.push(`        ${this.gateToQSharp(g)}`);
    }

    lines.push('');
    lines.push('        // Dump quantum statevector to diagnostic console');
    lines.push('        DumpMachine();');
    lines.push('');
    lines.push('        // Measure all qubits and reset to ground state |0⟩');
    lines.push('        mutable results = [];');
    lines.push('        for q in qs {');
    lines.push('            set results += [MResetZ(q)];');
    lines.push('        }');
    lines.push('        return results;');
    lines.push('    }');
    lines.push('}');

    return lines.join('\n');
  }

  private static gateToQSharp(g: GatePlacement): string {
    const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
    switch (type) {
      case 'H':
        return `H(qs[${qubit}]);`;
      case 'X':
        return `X(qs[${qubit}]);`;
      case 'Y':
        return `Y(qs[${qubit}]);`;
      case 'Z':
        return `Z(qs[${qubit}]);`;
      case 'S':
        return `S(qs[${qubit}]);`;
      case 'T':
        return `T(qs[${qubit}]);`;
      case 'Sdg':
        return `Adjoint S(qs[${qubit}]);`;
      case 'Tdg':
        return `Adjoint T(qs[${qubit}]);`;
      case 'Rx':
        return `Rx(${param.toFixed(4)}, qs[${qubit}]);`;
      case 'Ry':
        return `Ry(${param.toFixed(4)}, qs[${qubit}]);`;
      case 'Rz':
        return `Rz(${param.toFixed(4)}, qs[${qubit}]);`;
      case 'CX':
        return `CNOT(qs[${controlQubit}], qs[${qubit}]);`;
      case 'CZ':
        return `CZ(qs[${controlQubit}], qs[${qubit}]);`;
      case 'SWAP':
        return `SWAP(qs[${qubit}], qs[${targetQubit}]);`;
      case 'CCX':
        return `CCNOT(qs[${controlQubit}], qs[${controlQubit2}], qs[${qubit}]);`;
      case 'M':
        return `let m${qubit} = M(qs[${qubit}]);`;
      default:
        return `// Unsupported gate: ${type}`;
    }
  }

  /**
   * 7. Transpile to QuTiP (Quantum Toolbox in Python)
   */
  static toQutip(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — QuTiP (Quantum Toolbox in Python)',
      'import qutip as qt',
      'import numpy as np',
      '',
      `# Initial ground state |0...0⟩ across ${numQubits} qubits`,
      `psi0 = qt.tensor([qt.basis(2, 0) for _ in range(${numQubits})])`,
      '',
      '# Gate operators definition helper',
      'def single_qubit_gate(gate, target, N):',
      '    ops = [qt.qeye(2)] * N',
      '    ops[target] = gate',
      '    return qt.tensor(ops)',
      '',
      'state = psi0',
    ];

    for (const g of sorted) {
      const { type, qubit, controlQubit, targetQubit, param = 0 } = g;
      switch (type) {
        case 'H':
          lines.push(`state = single_qubit_gate(qt.splay(qt.hadamard_transform()), ${qubit}, ${numQubits}) * state`
            .replace('qt.splay(qt.hadamard_transform())', '(qt.sigmax() + qt.sigmaz()) / np.sqrt(2)'));
          break;
        case 'X':
          lines.push(`state = single_qubit_gate(qt.sigmax(), ${qubit}, ${numQubits}) * state`);
          break;
        case 'Y':
          lines.push(`state = single_qubit_gate(qt.sigmay(), ${qubit}, ${numQubits}) * state`);
          break;
        case 'Z':
          lines.push(`state = single_qubit_gate(qt.sigmaz(), ${qubit}, ${numQubits}) * state`);
          break;
        case 'S':
          lines.push(`state = single_qubit_gate(qt.phasegate(np.pi/2), ${qubit}, ${numQubits}) * state`);
          break;
        case 'T':
          lines.push(`state = single_qubit_gate(qt.phasegate(np.pi/4), ${qubit}, ${numQubits}) * state`);
          break;
        case 'Rx':
          lines.push(`state = single_qubit_gate(qt.rotation(qt.sigmax(), ${param.toFixed(4)}), ${qubit}, ${numQubits}) * state`);
          break;
        case 'Ry':
          lines.push(`state = single_qubit_gate(qt.rotation(qt.sigmay(), ${param.toFixed(4)}), ${qubit}, ${numQubits}) * state`);
          break;
        case 'Rz':
          lines.push(`state = single_qubit_gate(qt.rotation(qt.sigmaz(), ${param.toFixed(4)}), ${qubit}, ${numQubits}) * state`);
          break;
        case 'CX':
          lines.push(`# CNOT gate (control: ${controlQubit}, target: ${qubit})`);
          lines.push(`cnot_op = qt.cnot(N=${numQubits}, control=${controlQubit}, target=${qubit}) if hasattr(qt, 'cnot') else single_qubit_gate(qt.sigmax(), ${qubit}, ${numQubits})`);
          lines.push(`state = cnot_op * state`);
          break;
        case 'CZ':
          lines.push(`# CZ gate (control: ${controlQubit}, target: ${qubit})`);
          lines.push(`cz_op = qt.cz_gate(N=${numQubits}, control=${controlQubit}, target=${qubit}) if hasattr(qt, 'cz_gate') else single_qubit_gate(qt.sigmaz(), ${qubit}, ${numQubits})`);
          lines.push(`state = cz_op * state`);
          break;
        case 'SWAP':
          lines.push(`state = qt.swap(N=${numQubits}, targets=[${qubit}, ${targetQubit}]) * state`);
          break;
        default:
          break;
      }
    }

    lines.push('');
    lines.push('print("QuTiP State Vector:\\n", state)');
    lines.push('print("Density Matrix:\\n", qt.ket2dm(state))');

    return lines.join('\n');
  }

  /**
   * 8. Transpile to PyQuil (Rigetti Forest)
   */
  static toPyQuil(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      '# Generated by QubitLearn AI — Rigetti pyQuil SDK',
      'from pyquil import Program',
      'from pyquil.gates import H, X, Y, Z, S, T, RX, RY, RZ, CNOT, CZ, SWAP, CCNOT, MEASURE',
      'from pyquil.api import WavefunctionSimulator',
      '',
      'p = Program()',
    ];

    for (const g of sorted) {
      const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
      switch (type) {
        case 'H':
          lines.push(`p += H(${qubit})`);
          break;
        case 'X':
          lines.push(`p += X(${qubit})`);
          break;
        case 'Y':
          lines.push(`p += Y(${qubit})`);
          break;
        case 'Z':
          lines.push(`p += Z(${qubit})`);
          break;
        case 'S':
          lines.push(`p += S(${qubit})`);
          break;
        case 'T':
          lines.push(`p += T(${qubit})`);
          break;
        case 'Rx':
          lines.push(`p += RX(${param.toFixed(4)}, ${qubit})`);
          break;
        case 'Ry':
          lines.push(`p += RY(${param.toFixed(4)}, ${qubit})`);
          break;
        case 'Rz':
          lines.push(`p += RZ(${param.toFixed(4)}, ${qubit})`);
          break;
        case 'CX':
          lines.push(`p += CNOT(${controlQubit}, ${qubit})`);
          break;
        case 'CZ':
          lines.push(`p += CZ(${controlQubit}, ${qubit})`);
          break;
        case 'SWAP':
          lines.push(`p += SWAP(${qubit}, ${targetQubit})`);
          break;
        case 'CCX':
          lines.push(`p += CCNOT(${controlQubit}, ${controlQubit2}, ${qubit})`);
          break;
        default:
          break;
      }
    }

    lines.push('');
    lines.push('# Run statevector simulation');
    lines.push('wfn = WavefunctionSimulator().wavefunction(p)');
    lines.push('print("pyQuil State Amplitudes:\\n", wfn.amplitudes)');

    return lines.join('\n');
  }

  /**
   * 9. Export to OpenQASM 3.0 / 2.0
   */
  static toOpenQasm(circuit: CircuitState): string {
    const { numQubits, gates } = circuit;
    const sorted = [...gates].sort((a, b) => a.timeStep - b.timeStep);

    const lines: string[] = [
      'OPENQASM 2.0;',
      'include "qelib1.inc";',
      `qreg q[${numQubits}];`,
      `creg c[${numQubits}];`,
      '',
    ];

    for (const g of sorted) {
      const { type, qubit, controlQubit, controlQubit2, targetQubit, param = 0 } = g;
      switch (type) {
        case 'H':
          lines.push(`h q[${qubit}];`);
          break;
        case 'X':
          lines.push(`x q[${qubit}];`);
          break;
        case 'Y':
          lines.push(`y q[${qubit}];`);
          break;
        case 'Z':
          lines.push(`z q[${qubit}];`);
          break;
        case 'S':
          lines.push(`s q[${qubit}];`);
          break;
        case 'T':
          lines.push(`t q[${qubit}];`);
          break;
        case 'Rx':
          lines.push(`rx(${param.toFixed(4)}) q[${qubit}];`);
          break;
        case 'Ry':
          lines.push(`ry(${param.toFixed(4)}) q[${qubit}];`);
          break;
        case 'Rz':
          lines.push(`rz(${param.toFixed(4)}) q[${qubit}];`);
          break;
        case 'CX':
          lines.push(`cx q[${controlQubit}], q[${qubit}];`);
          break;
        case 'CZ':
          lines.push(`cz q[${controlQubit}], q[${qubit}];`);
          break;
        case 'SWAP':
          lines.push(`swap q[${qubit}], q[${targetQubit}];`);
          break;
        case 'CCX':
          lines.push(`ccx q[${controlQubit}], q[${controlQubit2}], q[${qubit}];`);
          break;
        case 'M':
          lines.push(`measure q[${qubit}] -> c[${qubit}];`);
          break;
      }
    }

    return lines.join('\n');
  }

  /**
   * 10. Export to Publication-ready LaTeX quantikz
   */
  static toQuantikz(circuit: CircuitState): string {
    const { numQubits, timeSteps, gates } = circuit;

    const grid: string[][] = Array.from({ length: numQubits }, () =>
      Array.from({ length: timeSteps }, () => '\\qw')
    );

    for (const g of gates) {
      const { type, qubit, timeStep, controlQubit, targetQubit } = g;
      if (qubit >= numQubits || timeStep >= timeSteps) continue;

      if (type === 'H') grid[qubit][timeStep] = '\\gate{H}';
      else if (type === 'X') grid[qubit][timeStep] = '\\gate{X}';
      else if (type === 'Y') grid[qubit][timeStep] = '\\gate{Y}';
      else if (type === 'Z') grid[qubit][timeStep] = '\\gate{Z}';
      else if (type === 'S') grid[qubit][timeStep] = '\\gate{S}';
      else if (type === 'T') grid[qubit][timeStep] = '\\gate{T}';
      else if (type === 'CX' && controlQubit !== undefined) {
        const offset = qubit - controlQubit;
        grid[controlQubit][timeStep] = `\\ctrl{${offset}}`;
        grid[qubit][timeStep] = '\\targ{}';
      } else if (type === 'CZ' && controlQubit !== undefined) {
        const offset = qubit - controlQubit;
        grid[controlQubit][timeStep] = `\\ctrl{${offset}}`;
        grid[qubit][timeStep] = '\\control{}';
      } else if (type === 'SWAP' && targetQubit !== undefined) {
        grid[qubit][timeStep] = `\\swap{${targetQubit - qubit}}`;
        grid[targetQubit][timeStep] = '\\targX{}';
      } else if (type === 'M') {
        grid[qubit][timeStep] = '\\meter{}';
      } else {
        grid[qubit][timeStep] = `\\gate{${type}}`;
      }
    }

    const rowStrings = grid.map(
      (row, idx) => `\\lstick{\\ket{q_{${idx}}}} & ${row.join(' & ')} & \\qw`
    );

    return [
      '% Publication-ready LaTeX quantikz circuit',
      '\\begin{quantikz}',
      rowStrings.join(' \\\\\n'),
      '\\end{quantikz}',
    ].join('\n');
  }

  /**
   * Parse code into visual CircuitState
   */
  static fromCode(code: string): CircuitState {
    const lines = code.split('\n');
    const gates: GatePlacement[] = [];
    let numQubits = 2;
    let timeStep = 0;

    const qcMatch = code.match(/QuantumCircuit\s*\(\s*(\d+)/);
    if (qcMatch) numQubits = Math.max(1, Math.min(5, parseInt(qcMatch[1], 10)));
    const qregMatch = code.match(/qreg\s+\w+\[(\d+)\]/);
    if (qregMatch) numQubits = Math.max(1, Math.min(5, parseInt(qregMatch[1], 10)));

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line || line.startsWith('#') || line.startsWith('//') || line.startsWith('OPENQASM') || line.startsWith('include')) {
        continue;
      }

      // Qiskit / Cirq / Braket single-qubit gates: qc.h(0) or circuit.h(0)
      const qkSingle = line.match(/(?:qc|circuit)\.([a-zA-Z]+)\s*\(\s*(\d+)\s*\)/);
      if (qkSingle) {
        const [, op, qStr] = qkSingle;
        const q = parseInt(qStr, 10);
        const opUpper = op.toUpperCase();
        const validTypes = ['H', 'X', 'Y', 'Z', 'S', 'T'];
        const type = validTypes.includes(opUpper) ? (opUpper as any) : opUpper === 'M' || opUpper === 'MEASURE' ? 'M' : 'H';
        gates.push({ id: `code-g-${gates.length}`, type, qubit: q, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      // CUDA-Q single gate: cudaq.h(q[0]) or h(q[0])
      const cudaSingle = line.match(/(?:cudaq\.)?([hxyzst])\s*\(\s*q\[(\d+)\]\s*\)/i);
      if (cudaSingle) {
        const [, op, qStr] = cudaSingle;
        const q = parseInt(qStr, 10);
        const type = op.toUpperCase() as any;
        gates.push({ id: `code-g-${gates.length}`, type, qubit: q, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      // Q# single gate: H(qs[0]);
      const qsSingle = line.match(/^([HXYZST])\s*\(\s*qs\[(\d+)\]\s*\);/);
      if (qsSingle) {
        const [, op, qStr] = qsSingle;
        const q = parseInt(qStr, 10);
        gates.push({ id: `code-g-${gates.length}`, type: op as any, qubit: q, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      // Qiskit / Braket CX: qc.cx(c, t) or circuit.cnot(c, t)
      const qkCX = line.match(/(?:qc|circuit)\.(?:cx|cnot)\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/);
      if (qkCX) {
        const [, cStr, tStr] = qkCX;
        const c = parseInt(cStr, 10);
        const t = parseInt(tStr, 10);
        gates.push({ id: `code-g-${gates.length}`, type: 'CX', qubit: t, controlQubit: c, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      // CUDA-Q cx: cudaq.cx(q[c], q[t]) or cx(q[c], q[t])
      const cudaCX = line.match(/(?:cudaq\.)?cx\s*\(\s*q\[(\d+)\]\s*,\s*q\[(\d+)\]\s*\)/i);
      if (cudaCX) {
        const [, cStr, tStr] = cudaCX;
        gates.push({ id: `code-g-${gates.length}`, type: 'CX', qubit: parseInt(tStr, 10), controlQubit: parseInt(cStr, 10), timeStep: Math.min(7, timeStep++) });
        continue;
      }

      // Q# CNOT: CNOT(qs[c], qs[t]);
      const qsCX = line.match(/^CNOT\s*\(\s*qs\[(\d+)\]\s*,\s*qs\[(\d+)\]\s*\);/);
      if (qsCX) {
        const [, cStr, tStr] = qsCX;
        gates.push({ id: `code-g-${gates.length}`, type: 'CX', qubit: parseInt(tStr, 10), controlQubit: parseInt(cStr, 10), timeStep: Math.min(7, timeStep++) });
        continue;
      }

      const qkCZ = line.match(/qc\.cz\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/);
      if (qkCZ) {
        const [, cStr, tStr] = qkCZ;
        const c = parseInt(cStr, 10);
        const t = parseInt(tStr, 10);
        gates.push({ id: `code-g-${gates.length}`, type: 'CZ', qubit: t, controlQubit: c, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      const qkSWAP = line.match(/qc\.swap\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/);
      if (qkSWAP) {
        const [, q1Str, q2Str] = qkSWAP;
        const q1 = parseInt(q1Str, 10);
        const q2 = parseInt(q2Str, 10);
        gates.push({ id: `code-g-${gates.length}`, type: 'SWAP', qubit: q1, targetQubit: q2, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      const qkRotation = line.match(/qc\.(rx|ry|rz)\s*\(\s*([0-9\.\-\*\/piPI]+)\s*,\s*(\d+)\s*\)/);
      if (qkRotation) {
        const [, op, paramStr, qStr] = qkRotation;
        const q = parseInt(qStr, 10);
        let param = 1.57;
        try {
          if (paramStr.includes('pi') || paramStr.includes('PI')) {
            param = Math.PI;
          } else {
            param = parseFloat(paramStr) || 1.57;
          }
        } catch {
          param = 1.57;
        }
        gates.push({ id: `code-g-${gates.length}`, type: op.toUpperCase() as any, qubit: q, param, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      const qasmSingle = line.match(/^([a-z]+)\s+\w+\[(\d+)\]\s*;/);
      if (qasmSingle) {
        const [, op, qStr] = qasmSingle;
        const q = parseInt(qStr, 10);
        const opUpper = op.toUpperCase();
        gates.push({ id: `code-g-${gates.length}`, type: (['H', 'X', 'Y', 'Z', 'S', 'T'].includes(opUpper) ? opUpper : 'H') as any, qubit: q, timeStep: Math.min(7, timeStep++) });
        continue;
      }

      const qasmCX = line.match(/^cx\s+\w+\[(\d+)\]\s*,\s*\w+\[(\d+)\]\s*;/);
      if (qasmCX) {
        const [, cStr, tStr] = qasmCX;
        gates.push({ id: `code-g-${gates.length}`, type: 'CX', qubit: parseInt(tStr, 10), controlQubit: parseInt(cStr, 10), timeStep: Math.min(7, timeStep++) });
        continue;
      }
    }

    return {
      numQubits,
      timeSteps: Math.max(6, timeStep + 1),
      gates,
    };
  }
}
